package hk.uwu.roxyhook.platform

enum class Capability {
    METHOD_HOOK, CONSTRUCTOR_HOOK, INVOKE_ORIGINAL, INTERCEPTOR_CHAIN, ATOMIC_REPLACEMENT,
    DEOPTIMIZATION, CLASS_INITIALIZER, HOT_RELOAD_KEEP, REMOTE_PREFERENCES, REMOTE_FILES
}
