package hk.uwu.roxyhook.ksp

object EntryRenderer {
    fun kotlin(model: EntryModel): String = """
        |package ${model.generatedPackage}
        |
        |// Generated by RoxyHook KSP. Edit the annotated module, not this file.
        |public class ${model.generatedName} : hk.uwu.roxyhook.platform.libxposed.RoxyXposedModule() {
        |    override val module: hk.uwu.roxyhook.RoxyModule = ${model.kotlinReference}${if (model.isObject) "" else "()"}
        |}
        |""".trimMargin()
    fun entryList(models: Collection<EntryModel>): String {
        require(models.size == 1) { "Exactly one @RoxyEntry is required per application compilation" }
        return models.single().generatedQualifiedName + "\n"
    }
    fun keepRules(model: EntryModel): String = """
        |-keep class ${model.generatedQualifiedName} { public <init>(); }
        |-dontwarn io.github.libxposed.annotation.**
        |""".trimMargin()
}
